version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - cd react-code-build
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:$ENVIRONMENT
  post_build:
    commands:
      - ls -ls
      - aws s3 sync  --debug ./build $S3_BUCKET
